### PR TITLE
wsl fix

### PR DESCRIPTION
**Pull request by jvegaf**
added cmd_open option for Windows Subsystem for Linux

### CODE REVIEW

**Review by lalitmee — APPROVED** [review]

**Comment by lalitmee** [comment]
Hey @jvegaf, thanks for the PR.

**Comment by amiroslaw** [comment]
@jvegaf, I think you forgot to invoke `is_wsl` in the if statement. It  should be `if is_wsl() then`.

**Comment by lalitmee** [comment]
@amiroslaw, yeah that makes sense. 

@jvegaf, can you please check and fix it?

**Comment by jvegaf** [comment]
> @amiroslaw, yeah that makes sense.
> 
> @jvegaf, can you please check and fix it?

of, course 👍

**Pull request merged**
